#quick chatbot
print("hi my name is jarvis. what is your name? ")
name = input("what is your name? ")
print(name)
print("how are you"  + name + "? ")
how=input("how are you ")
print("i am "+ how + ". ")
print("what iss your age"+ name +". ")
age=input("what is your age")
print(name + "what is your qualification? ")
past_qualification = input("what is your past qualification? ")
current_qualification =  input("what is your current qulification? ")
print("i have done"+ past_qualification + "and currently i am pursuing " +current_qualification)
print("wow that it wonderful to hear" + name)
print("lets perform a little exrecise with two numbers" )
what = input()
print("we just have to add two numbers" )
ans= input()
a = float(input("number 1 is :"))
b = float(input("number 2 is :"))
sum=a+b
print("the sum is "+ str(sum))
print(name+"you did great")
print("happy meeting you.\nbye. see you next time" )